### ISSUE TITLE
Clean Up

### ISSUE THREAD

**Issue by oph-design** [philippschwarzmueller/mini_shell#143]
**For vogsphere repository:**

- [x] Remove tests directory
- [x] Remove Github actions
- [x] Remove README
- [x] Add Header to every .c and .h file

**Comment by philippschwarzmueller** [comment]
I would do all that stuff on a local copy of the repo and Not push the chamges to github

**Comment by oph-design** [comment]
As we succeeded in the evaluation, I think this issue is done
