### ISSUE TITLE
Redirections need to work at every position of a cmd

### ISSUE THREAD

**Issue by philippschwarzmueller** [philippschwarzmueller/mini_shell#43]
`< {infile}` at any point of the command string needs to change the in-fd
`> {outfile}` at any point of the command string needs to change the out-fd

**Comment by oph-design** [comment]
May I interject for a moment. I noticed that our files in the parent process never get properly closed. Is it possible to update the free_cmd function, so that every file descriptor with a value above 2 gets closed when freeing the command?

**Comment by philippschwarzmueller** [comment]
Interesting thought! For the implementation of the heredoc i am currently rewriting the cmd struct anyway. So i will take that into consideration When doing so
