### ISSUE TITLE
add Expander

### ISSUE THREAD

**Issue by oph-design** [philippschwarzmueller/mini_shell#45]
**Story:**
As a person with bad memory and lots of money, I need the shell to be able to tell me my username by utilizing my favorite currency, so that I can ask the computer in case I forgot.

**Use Case:**
"echo $USER" outputs the username 

**Requirements:**
- [x] $... signals the use of an Enviromentvariable
- [x] options get expanded with value of said variable
- [x] if variable contains command, the command is executed
- [x] $... gets not expanded if inside single quotes (')
- [x] $... gets not expanded if $ is escaped

**Comment by philippschwarzmueller** [comment]
Small addition: also in and out files need to be expanded
